
title: Caleb Larsen's Site
description: >- # this means to ignore newlines until "baseurl:"
  A home for my projects and thoughts
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://caleblarsen.github.io"
github_username:  CalebLarsen

# Build settings
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - senseless/node_modules
  - senseless-src/

include: ["senseless/build"]
